apiVersion: apps/v1
kind: Deployment
metadata:
  name: receivedata
  labels:
    app: receivedata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receivedata
  template:
    metadata:
      labels:
        app: receivedata
    spec:
      containers:
        - name: receivedata
          imagePullPolicy: Always
          image: replace/me/receivedata
          env:
            - name: EVENTBUS_HOSTNAME
              value: 'eventbus'
            - name: EVENTBUS_PORT
              value: '4005'