apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: receivedata-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: receivedata-service
            port:
              number: 4000