apiVersion: v1
kind: Service
metadata:
  name: receivedata
  labels:
    app: receivedata
spec:
  type: NodePort
  selector:
    app: receivedata
  ports:
    - name: receivedata
      protocol: TCP
      port: 4000
      targetPort: 4000